repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=79"]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        args: ["--strict"]
        language: system
        types: [ python ]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
